columns:
  age             :  int64 
  workclass       :  object
  fnlwgt          :  int64 
  education_num   :  int64 
  marital_status  :  object
  occupation      :  object
  relationship    :  object
  race            :  object
  sex             :  object
  hours_per_week  :  int64 
  

TARGET_COLUMN:
  name: income  